aspnet/MyBlogApp/MyBlogApp/Models/Article.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MyBlogApp.Models
{
    public class Article
    {
        public int Id { get; set; }

        [Required]
        [DisplayName("タイトル")]
        public string Title { get; set; }

        [Required]
        [DisplayName("本文")]
        public string Body { get; set; }

        [DisplayName("投稿日")]
        public DateTime Created { get; set; }

        [DisplayName("更新日")]
        public DateTime Modified { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }

        public virtual Category Category { get; set; }

        [Required]
        [NotMapped]
        [DisplayName("カテゴリー")]
        public string CategoryName { get; set; }
    }
}

aspnet/MyBlogApp/MyBlogApp/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyBlogApp.Models;

namespace MyBlogApp.Controllers
{
    [CategoryFilter]
    public class ArticlesController : Controller
    {
        private BlogContext db = new BlogContext();

        // GET: Articles
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.Articles.OrderByDescending(item => item.Modified).ToList());

         //   var blogds = from s in db.Articles
         //               orderby s.Modified descending, s.Title
         //               select s;
         //   return View(blogds);
         //   return View(db.Articles.ToList());
        }

        // GET: Articles/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // GET: Articles/Create
        [Authorize(Roles = "Owners")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Articles/Create
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Owners")]
        public ActionResult Create([Bind(Include = "Id,Title,Body,CategoryName")] Article article)
        {
            if (ModelState.IsValid)
            {
                article.Created = DateTime.Now;
                article.Modified = DateTime.Now;

                // DBからカテゴリーを取得
                var category = db.Categories
                    .Where(item => item.CategoryName.Equals(article.CategoryName))
                    .FirstOrDefault();
                if (category == null)
                {
                    // カテゴリーを登録
                    category = new Category()
                    {
                        CategoryName = article.CategoryName,
                        Count = 1
                    };
                    db.Categories.Add(category);
                }
                else
                {
                    // カテゴリーを更新
                    category.Count++;
                    db.Entry(category).State = EntityState.Modified;
                }

                article.Category = category;

                db.Articles.Add(article);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(article);
        }

        // GET: Articles/Edit/5
        [Authorize(Roles = "Owners")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }

            article.CategoryName = article.Category.CategoryName;

            return View(article);
        }

        // POST: Articles/Edit/5
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Owners")]
        public ActionResult Edit([Bind(Include = "Id,Title,Body,CategoryName")] Article article)
        {
            if (ModelState.IsValid)
            {
                // DBから取得
                var dbArticle = db.Articles.Find(article.Id);
                if (dbArticle == null)
                {
                    return HttpNotFound();
                }

                // 更新内容を反映
                dbArticle.Title = article.Title;
                dbArticle.Body = article.Body;
                dbArticle.Modified = DateTime.Now;
                dbArticle.CategoryName = article.CategoryName;

                // カテゴリー変更
                var beforeCategory = dbArticle.Category;
                if (!beforeCategory.CategoryName.Equals(article.CategoryName))
                {
                    // 前カテゴリーを更新
                    beforeCategory.Articles.Remove(dbArticle);
                    beforeCategory.Count--;
                    db.Entry(beforeCategory).State = EntityState.Modified;

                    // 新カテゴリーを取得
                    var category = db.Categories
                        .Where(item => item.CategoryName.Equals(article.CategoryName))
                        .FirstOrDefault();

                    if (category == null)
                    {
                        // 新カテゴリーを追加
                        category = new Category()
                        {
                            CategoryName = article.CategoryName,
                            Count = 1
                        };
                        db.Categories.Add(category);
                    }
                    else
                    {
                        // 新カテゴリーを更新
                        category.Count++;
                        db.Entry(category).State = EntityState.Modified;
                    }

                    // 新カテゴリーを記事と紐づけ
                    dbArticle.Category = category;
                }

                db.Entry(dbArticle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(article);
        }

        // GET: Articles/Delete/5
        [Authorize(Roles = "Owners")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Owners")]
        public ActionResult DeleteConfirmed(int id)
        {
            Article article = db.Articles.Find(id);

            // カテゴリーの件数を-1
            Category category = article.Category;
            category.Count--;
            db.Entry(category).State = EntityState.Modified;

            // コメントを削除
            article.Comments.Clear();
            
            db.Articles.Remove(article);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Articles/CreateComment
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult CreateComment([Bind(Include = "ArticleId,Body")] Comment comment)
        {
            var article = db.Articles.Find(comment.ArticleId);
            if (article == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            comment.Created = DateTime.Now;
            comment.Article = article;

            db.Comments.Add(comment);
            db.SaveChanges();

            return RedirectToAction("Details", new { id = comment.ArticleId });
        }

        // GET: Articles/DeleteComment/5
        [Authorize(Roles = "Owners")]
        public ActionResult DeleteComment(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Articles/DeleteComment/5
        [HttpPost, ActionName("DeleteComment")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Owners")]
        public ActionResult DeleteCommentConfirmed(int id)
        {
            var comment = db.Comments.Find(id);
            int articleId = comment.Article.Id;

            db.Comments.Remove(comment);
            db.SaveChanges();

            return RedirectToAction("Details", new { id = articleId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

aspnet/MyBlogApp/MyBlogApp/Views/Articles/Create.cshtml
@using MyBlogApp.Models
@model MyBlogApp.Models.Article

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/_LayoutPage1.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control", list = "categories" } })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })

                <datalist id="categories">
                    @{ 
                        var categories = (List<Category>)ViewBag.Categories;
                        foreach(var item in categories)
                        {
                            <option>@Html.DisplayFor(modelItem => item.CategoryName)</option>
                        }
                    }
                </datalist>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

aspnet/MyBlogApp/MyBlogApp/Views/Articles/Delete.cshtml
@model MyBlogApp.Models.Article

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/_LayoutPage1.cshtml";
}

<h2>Delete</h2>

<h3>本当に削除しますか？?</h3>
<div>
    <h4>Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modified)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="削除" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

aspnet/MyBlogApp/MyBlogApp/Views/Articles/DeleteComment.cshtml
@model MyBlogApp.Models.Comment

@{
    ViewBag.Title = "DeleteComment";
    Layout = "~/Views/_LayoutPage1.cshtml";
}

<h2>DeleteComment</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Comment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

aspnet/MyBlogApp/MyBlogApp/Views/Articles/Details.cshtml
@using MyBlogApp.Models
@model MyBlogApp.Models.Article

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/_LayoutPage1.cshtml";
}

<div>

    <div class="page-header">
        <h2>@Html.DisplayFor(model => model.Title)</h2>
    </div>
    <p class="text-muted">
        @Html.DisplayNameFor(model => model.Category.CategoryName):
        @if (Model.Category != null)
        {
            @Html.ActionLink(Model.Category.CategoryName, "Details", new { id = Model.Category.Id, Controller = "Categories" })
        }
        else
        {
            <span>なし</span>
        }
    </p>

    <div class="lead">
        @Html.DisplayFor(model => model.Body)
    </div>

    <div class="text-right text-muted">
        @Html.DisplayNameFor(model => model.Created):
        @Html.DisplayFor(model => model.Created)

        @if (Model.Modified != null)
        {
            @Html.DisplayNameFor(model => model.Modified)<span>:</span>
            @Html.DisplayFor(model => model.Modified)
        }

        @if (User.IsInRole("Owners"))
        {
            @Html.ActionLink("更新", "Edit", new { id = Model.Id }, new { @class = "btn btn-xs btn-info" })
            @Html.ActionLink("削除", "Delete", new { id = Model.Id }, new { @class = "btn btn-xs btn-danger" })
        }
    </div>

    <hr />
    
    @using (@Html.BeginForm("CreateComment", "Articles"))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("ArticleId", Model.Id)
        <div class="form-group">
            @Html.TextArea("Body", "", new { @class = "form-control", placeholder = "コメント", rows = 3 })
        </div>
        <input type="submit" value="投稿" class="btn btn-default" />
    }

    @foreach (Comment item in Model.Comments)
    {
        <div class="panel panel-default">
            <div class="panel-body">@Html.DisplayFor(model => item.Body)</div>
            <div class="panel-footer text-right">
                <span class="text-muted">
                    @Html.DisplayNameFor(model => item.Created):
                    @Html.DisplayFor(model => item.Created)
                </span>
                @if (User.IsInRole("Owners"))
                {
                    @Html.ActionLink("削除", "DeleteComment", new { id = item.Id }, new { @class = "btn btn-xs btn-danger" })
                }
            </div>
        </div>
    }
</div>

aspnet/MyBlogApp/MyBlogApp/Views/Articles/Edit.cshtml
@using MyBlogApp.Models
@model MyBlogApp.Models.Article

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/_LayoutPage1.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control", list = "categories" } })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
                <datalist id="categories">
                    @{
                        var categories = (List<Category>)ViewBag.Categories;
                        foreach (var item in categories)
                        {
                            <option>@Html.DisplayFor(modelItem => item.CategoryName)</option>
                        }
                    }
                </datalist>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

aspnet/MyBlogApp/MyBlogApp/Views/Articles/Index.cshtml
@model IEnumerable<MyBlogApp.Models.Article>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_LayoutPage1.cshtml";
}

@foreach (var item in Model) {
    <div class="panel panel-default">
        <div class="panel-heading">
            @Html.DisplayFor(model => item.Title)
        </div>
        <div class="panel-body">
            <div class="article-body">
                @Html.DisplayFor(model => item.Body)
            </div>
            <div class="text-right text-muted">
                @Html.ActionLink("続きを読む", "Details", new { id = item.Id })
            </div>
        </div>
        <div class="panel-footer text-right">
            @Html.DisplayNameFor(model => model.CategoryName):
            @Html.ActionLink(item.Category.CategoryName, "Details", new { id = item.Category.Id, Controller = "Categories" })
            
            @Html.DisplayNameFor(model => model.Created):
            @Html.DisplayFor(modelItem => item.Created)

            @if (item.Modified != null)
            {
                @Html.DisplayNameFor(model => model.Modified)<span>:</span>
                @Html.DisplayFor(modelItem => item.Modified)
            }
    </div>

</div>
}